# Generated by Django 5.1.5 on 2025-02-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0002_task_assigned_by_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'Urgent'), ('2', 'High Priority'), ('3', 'Medium Priority'), ('4', 'Low Priority')], default='3', max_length=1),
        ),
    ]
